name: fpc
description: QQ/TIM FlashPicture Getter.

version: 1.0.5+23

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_local_notifications: 0.8.2
  path_provider: 0.5.0
  permission_handler: 3.2.2
  shared_preferences: ^0.5.6
  fluttertoast: ^3.1.3
  open_file: 2.0.3

flutter:
  uses-material-design: true
